# Generated by Django 5.1.7 on 2025-06-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Import_User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=1000)),
                ('ProfilePic', models.ImageField(upload_to='ImportUser/')),
                ('Address', models.CharField(max_length=1000)),
                ('Country', models.CharField(max_length=1000)),
                ('State', models.CharField(max_length=1000)),
                ('City', models.CharField(max_length=1000)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
