# Generated by Django 5.1.7 on 2025-06-16 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_department_users_data'),
        ('products', '0002_alter_category_category_img_alter_products_dealer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Import_User',
        ),
        migrations.AddField(
            model_name='users_data',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.department'),
        ),
    ]
